### ISSUE TITLE
数据写入失败，没有触发回调接口

### ISSUE THREAD

**Issue by ezlhq** [aliyun/aliyun-tsdb-java-sdk#16]
我使用的版本是 0.0.13
我使用以下配置去创建tsdbconfig
```
listenBatchPut(new BatchPutDetailsCallback() {
                @Override
                public void response(String address, List<Point> points, DetailsResult result) {
                    System.out.println(result);
                }
            })
```

当我使用异步写入接口，写入数据到TSDB数据库时，由于发送point不符合规范，写入失败，但是这个回调接口并没有触发。

**Comment by xiaowing** [comment]
`BatchPutDetailsCallback`的`response()`方法是指写入请求被成功执行，返回的详细信息是写入过程中写入成功/失败的点的情况

但对于数据格式不符合规范，会导致这个写入请求直接在服务端被拒绝掉。若要在这种情况下执行回调，需要实现 `BatchPutDetailsCallback#failed()`方法
