### ISSUE TITLE
写入数据丢失

### ISSUE THREAD

**Issue by yzpangu** [aliyun/aliyun-tsdb-java-sdk#29]
hi，目前我们的写入量大概相当于200个/s。出现了问题：没有报错，但是opentsdb数据量本来有140万，查询才有20多万，其他数据丢失了。
.listenBatchPut(new BatchPutCallback() {
					@Override
					public void response(String arg0, List<Point> arg1, Result arg2) {
					    if (arg2 != null) {
					        logger.info("tsd sync callback. " + arg2.toString());
                        }
					}
				}).config(); // 构造HiTSDBConfig对象
		return HiTSDBClientFactory.connect(config);

——————————————————————————————————————

如上代码打出的日志为：
[2019-02-28 00:00:05,479] [I/O dispatcher 3] [INFO] [opentsdb] [////] - [tsd sync callback. {}]

**Comment by xiaowing** [comment]
异步写入逻辑先前有不少问题，可以使用目前的最新版本再测试一下。
