### ISSUE TITLE
查询接口不支持指定useCalendar和timezone

### ISSUE THREAD

**Issue by clairedidi** [aliyun/aliyun-tsdb-java-sdk#34]
由于TSDB查询的时间范围有两种方式，一种是基于模的方式，一种是基于日历的方式，客户端中提供的查询Query不能指定useCalendar和timezone，这样的话在downsample的时候取得的结果都是根据UTC时间进行降采样的。我想得到的结果是北京时区的采样点，请问应该怎么做？
举个例子，我想查询北京时间6月22号到6月23号这一天的总和，如果不指定useCalendar和timezone的话，得到的结果点是北京时间6月22号8点-北京时间6月23号8点之间的总和，并不能达到我要的结果
![image](https://user-images.githubusercontent.com/5006117/61113525-0de0f200-a4c1-11e9-9b36-e2370c776a08.png)

**Comment by hujianhong** [comment]
这个可以参考文档：https://help.aliyun.com/document_detail/60683.html?spm=a2c4g.11186623.2.11.b6124ac8v0a0pa#h2--downsample-6

![image](https://user-images.githubusercontent.com/20662146/68355868-9f98fd00-014b-11ea-8744-9c6d7c2120ef.png)

以你的case为例：只需要将“1440m-sum-zero"修改为：“1440mc-sum-zero“即可；
