### ISSUE TITLE
最新的 0.3.0 版本的 Maven 仓库文件不全导致无法引用该版本的依赖。

### ISSUE THREAD

**Issue by vancepym** [aliyun/aliyun-tsdb-java-sdk#74]
仓库中缺少 JAR 文件，参见
* https://repo1.maven.org/maven2/com/aliyun/hitsdb-client/0.3.0/

**Comment by xiaowing** [comment]
@vancepym 感谢反馈。作为修复，已经发布了一个新的版本 0.3.1，请试用
